//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_info
    {
        public string ISBN { get; set; }
        public string book_name { get; set; }
        public string author { get; set; }
        public string press { get; set; }
        public string edition { get; set; }
        public string publish_time { get; set; }
        public Nullable<float> price { get; set; }
        public int category_id { get; set; }
    
        public virtual category_info category_info { get; set; }
    }
}
