//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_info
    {
        public category_info()
        {
            this.book_info = new HashSet<book_info>();
        }
    
        public int category_id { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<book_info> book_info { get; set; }
    }
}
